### ISSUE TITLE
Map Matching Issues

### ISSUE THREAD

**Issue by MrXo** [mapillary/map_matching_plus#7]
Great work you have done here, thank you for sharing!

I'm currently trying to map some data I have, but cannot produce the expected results, despite tuning the parameters of the mapping requests. You can have a look on the GPS positions I'm trying to map [here](http://bl.ocks.org/d/6b11e06b1cef1a204954b4997fe16310). Starting point is in the south.

Please ignore the fact, that the data seems to have a drift by some offset. I'm investigating on this issue but need some helpful tips if this drift isn't present in other datasets.

Here you can see my best mapping approach. [Track](http://bl.ocks.org/d/6f20c6e1afbb4cce6efc7be2d76acb86), Parameters: max_route_distance_factor=10&sigma_z=20&search_radius=5000&turn_penalty_factor=400&breakage_distance=3000&mode=auto

This is from the standard config with minimal adjustments. [Track](http://bl.ocks.org/d/2e30776024cfb56a0f6388537e406cee), Parameters: search_radius=5000&mode=auto

And here is the most hilarious result. However, it is the only one that connects the two sections. [Track](http://bl.ocks.org/d/620ddef4c8924fac8f3411a468864c23), Parameters: max_route_distance_factor=60&sigma_z=200&search_radius=5000&turn_penalty_factor=200&breakage_distance=6000&mode=auto

With human eyes, the GPS track should be obvious (or is it just because I know the locations?). However, the mapper seems to have big problems. Can you give me some hints for a better configuration so that it correctly maps the given positions?

Thanks in advance for your help!

**Comment by ptpt** [comment]
Hi @MrXo thanks for the impressive bug reporting.

 Have you set `max_search_radius` to 5000 meters in the configuration? It is likely the correct edge candidate to A8 is still out of search radius, although you set search_radius to be 5000 meters. `max_search_radius` limits the high user input search radius (to 100 meters by default), i.e. the final search radius will be `min(user input search radius, max_search_radius)`.

See https://github.com/mapillary/map_matching_plus/blob/master/docs/configuration.md#map-matching-parameters

**Comment by MrXo** [comment]
Ah, thank you, that's it! I had a look at all the parameters in the documentation except this one. The mapper now produces the expected result. I also tested the algorithm with my GPS, corrected by a certain drift and the original configuration, which also works fine.

Keep up the good work!
